### ISSUE TITLE
Couldn't train QuaNet on multiclass data

### ISSUE THREAD

**Issue by vickysvicky** [HLT-ISTI/QuaPy#14]
Hi, I am having trouble in training a QuaNet quantifier for multiclass (20) data. Everything works fine with where my dataset only has 2 classes. It looks like the ACC quantifier is not able to aggregate from more than 2 classes?

The classifier is built and trained as with the code below

```
classifier = LSTMnet(dataset.vocabulary_size, dataset.n_classes)
learner = NeuralClassifierTrainer(classifier)
learner.fit(*dataset.training.Xy)
```
where it has all the default configurations

> {'embedding_size': 100, 'hidden_size': 256, 'repr_size': 100, 'lstm_class_nlayers': 1, 'drop_p': 0.5}

Then I tried to train QuaNet with following code

```
model = QuaNetTrainer(learner, qp.environ['SAMPLE_SIZE'])
model.fit(dataset.training, fit_learner=False)
```

and it showed that QuaNet is built as

> QuaNetModule(
>   (lstm): LSTM(120, 64, batch_first=True, dropout=0.5, bidirectional=True)
>   (dropout): Dropout(p=0.5, inplace=False)
>   (ff_layers): ModuleList(
>     (0): Linear(in_features=208, out_features=1024, bias=True)
>     (1): Linear(in_features=1024, out_features=512, bias=True)
>   )
>   (output): Linear(in_features=512, out_features=20, bias=True)
> )

And then the error occured in `model.fit()`.

Attached is the error I get.

> Traceback (most recent call last):
>   File "quanet-test.py", line 181, in <module>
>     model.fit(dataset.training, fit_learner=False)
>   File "/home/vickys/.local/lib/python3.6/site-packages/quapy/method/neural.py", line 126, in fit
>     self.epoch(train_data_embed, train_posteriors, self.tr_iter, epoch_i, early_stop, train=True)
>   File "/home/vickys/.local/lib/python3.6/site-packages/quapy/method/neural.py", line 182, in epoch
>     quant_estims = self.get_aggregative_estims(sample_posteriors)
>   File "/home/vickys/.local/lib/python3.6/site-packages/quapy/method/neural.py", line 145, in get_aggregative_estims
>     prevs_estim.extend(quantifier.aggregate(predictions))
>   File "/home/vickys/.local/lib/python3.6/site-packages/quapy/method/aggregative.py", line 238, in aggregate
>     return ACC.solve_adjustment(self.Pte_cond_estim_, prevs_estim)
>   File "/home/vickys/.local/lib/python3.6/site-packages/quapy/method/aggregative.py", line 246, in solve_adjustment
>     adjusted_prevs = np.linalg.solve(A, B)
>   File "<__array_function__ internals>", line 6, in solve
>   File "/usr/local/lib64/python3.6/site-packages/numpy/linalg/linalg.py", line 394, in solve
>     r = gufunc(a, b, signature=signature, extobj=extobj)
>   ValueError: solve1: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m)->(m) (size 2 is different from 20)

Thank you!

**Comment by AlexMoreo** [comment]
Hi!

You are perfectly right, there was a bug. I have never tried the NeuralClassifierTrainer with multiclass problems (the main reason being that QuaNet was originally proposed as a binary quantifier), sorry for that!

The following code now works for me:

```
import numpy as np
from sklearn.datasets import fetch_20newsgroups

import quapy as qp
from classification.neural import LSTMnet, NeuralClassifierTrainer
from data import LabelledCollection, Dataset
from method.neural import QuaNetTrainer


qp.environ['SAMPLE_SIZE'] = 200

news_tr = fetch_20newsgroups(subset='train')
news_te = fetch_20newsgroups(subset='test')
news_tr = LabelledCollection(instances=news_tr.data, labels=news_tr.target, classes_=np.arange(20))
news_te = LabelledCollection(instances=news_te.data, labels=news_te.target, classes_=np.arange(20))
dataset = Dataset(news_tr, news_te)
qp.data.preprocessing.index(dataset, min_df=5, inplace=True)

classifier = LSTMnet(dataset.vocabulary_size, dataset.n_classes)
learner = NeuralClassifierTrainer(classifier)
learner.fit(*dataset.training.Xy)

model = QuaNetTrainer(learner, qp.environ['SAMPLE_SIZE'])
model.fit(dataset.training, fit_learner=False)
```

I have pushed the fix. Hope this helps!

Cheers

**Comment by AlexMoreo** [comment]
Let me know if this has solved the issue so I can close it.
Regards!

**Comment by vickysvicky** [comment]
Thanks Alex! That solves the problem!

Also another bug happened after doing a fresh pull.

> Traceback (most recent call last):
>
>
>   File "quanet-test.py", line 20, in <module>
>     import quapy as qp
>   File "/home/vickys/.local/lib/python3.6/site-packages/quapy/__init__.py", line 5, in <module>
>     from . import method
>   File "/home/vickys/.local/lib/python3.6/site-packages/quapy/method/__init__.py", line 3, in <module>
>     from . import meta
>   File "/home/vickys/.local/lib/python3.6/site-packages/quapy/method/meta.py", line 13, in <module>
>     from quapy.model_selection import GridSearchQ
>   File "/home/vickys/.local/lib/python3.6/site-packages/quapy/model_selection.py", line 14, in <module>
>     from util import _check_sample_size
> ModuleNotFoundError: No module named 'util'

I changed the line in `model_selection.py` from `from util import _check_sample_size` to `from quapy.util import _check_sample_size` and that fixed it for me.

**Comment by AlexMoreo** [comment]
Right! I have also pushed this suggestion. Thanks!
