### ISSUE TITLE
Dependencies that miss and have mismatched versions

### ISSUE THREAD

**Issue by mirkobunse** [HLT-ISTI/QuaPy#34]
A new, plain installation of QuaPy is currently not importable without installing an additional dependency (certifi) and a specific version of another dependency (matplotlib v3.8).

Steps to reproduce:

```sh
python -m venv venv
venv/bin/pip install quapy
venv/bin/python -c "import quapy"
```

Leads to `ModuleNotFoundError: No module named 'certifi'`.

Calling

```sh
venv/bin/pip install certifi
venv/bin/python -c "import quapy"
```

fixes the first issue but now leads to `ImportError: cannot import name 'get_cmap' from 'matplotlib.cm'`.

This second issue is resolved by explicitly installing a previous version of matplotlib:

```sh
venv/bin/pip install matplotlib==3.8
```

My suggestion for the certifi issue is to add a corresponding entry to `setup.py`. My suggestion for the second issue is to use a variant of `get_cmap` that is available in older versions and in the current version of matplotlib.

**Comment by AlexMoreo** [comment]
Solved! thanks!
