### ISSUE TITLE
Wiki correction

### ISSUE THREAD

**Issue by pglez82** [HLT-ISTI/QuaPy#4]
In the last part of the Methods wiki page, where it says:

`from classification.neural import NeuralClassifierTrainer, CNNnet`

I think it should say:

`from quapy.classification.neural import NeuralClassifierTrainer, LSTMnet`

**Comment by AlexMoreo** [comment]
Right. I am correcting the import. I leave the CNN instead of the LSTM to show an example of QuaNet with learners other than the ones discussed in the original article.
