### ISSUE TITLE
Multi-label support

### ISSUE THREAD

**Issue by 4kills** [HLT-ISTI/QuaPy#45]
I wanted to kindly ask, whether there is multi-label support planned to expand on the currently available multi-class functionality?

**Comment by AlexMoreo** [comment]
Hi 4kills,

It is in my TODO list, but it may take some time. In the meantime, we have been working on multi-label quantification in a different repository, a clone of quapy that you can find here:
https://github.com/manuel-francisco/quapy-ml/tree/main

This repo contains all the code for reproducing the experiments of the (open-access) paper:
https://dl.acm.org/doi/full/10.1145/3606264

Let me know if this helps.

Best regards,
Alex
