### ISSUE TITLE
Parameter fit_learner in QuaNetTrainer (fit method)

### ISSUE THREAD

**Issue by pglez82** [HLT-ISTI/QuaPy#5]
The parameter `fit_leaner` is not used in the function:

`def fit(self, data: LabelledCollection, fit_learner=True):`

and the learner is fitted every time:

`self.learner.fit(*classifier_data.Xy)`

**Comment by AlexMoreo** [comment]
Thanks for noticing this! Solved (b4aeaa97b7ea3709d333ec813b3c84fc57043fc2)
